apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus1
  template:
    metadata:
      labels:
        app: eventbus1
    spec:
      containers:
        - name: eventbus1
          image: hodujacloud/heleneventbus1

---
apiVersion: v1
kind: Service
metadata:
  name: eventbus1-srv
spec:
  selector:
    app: eventbus1
  ports:
    - name: eventbus1
      protocol: TCP
      port: 4005
      targetPort: 4005
